#!/usr/bin/python3

from pymongo import MongoClient


def insert_db(rest_list, price_range):
    client = MongoClient()
    db = client.test_2
    insert_dict = {}
    insert_dict['_id'] = price_range
    insert_dict['data'] = rest_list
    print(insert_dict)
    
    result = db.restaurants.insert_one(insert_dict)



if __name__ == '__main__':
    price_range = '3'
    rest_list = [{'composite': 78.91,
  'location': '401 13th St, San Francisco, CA 94130, United States',
  'name': 'Aracely Cafe',
  'price_range': 1,
  'rating_weight': 40.5,
  'standard_rating': 0.75,
  'total_reviews': 153},
 {'composite': 80.88,
  'location': 'San Francisco, CA 94105, United States',
  'name': 'The Chairman Truck',
  'price_range': 1,
  'rating_weight': 155.25,
  'standard_rating': 0.9,
  'total_reviews': 1481},
 {'composite': 91.03,
  'location': 'San Francisco, CA 94105, United States',
  'name': 'Primavera',
  'price_range': 1,
  'rating_weight': 82.35,
  'standard_rating': 0.94,
  'total_reviews': 262},
 {'composite': 82.41,
  'location': '91 Drumm St, San Francisco, CA 94111, United States',
  'name': 'Oasis Grill',
  'price_range': 1,
  'rating_weight': 480.6,
  'standard_rating': 0.89,
  'total_reviews': 1467},
 {'composite': 89.47,
  'location': '300 Francisco St, San Francisco, CA 94133, United States',
  'name': "Freddie's Sandwiches",
  'price_range': 1,
  'rating_weight': 167.4,
  'standard_rating': 0.88,
  'total_reviews': 514},
 {'composite': 90.56,
  'location': '542 Green St, San Francisco, CA 94133, United States',
  'name': 'Golden Boy Pizza',
  'price_range': 1,
  'rating_weight': 1186.65,
  'standard_rating': 0.92,
  'total_reviews': 3492},
 {'composite': 84.28,
  'location': '121 Spear St, San Francisco, CA 94105, United States',
  'name': 'eatsa',
  'price_range': 1,
  'rating_weight': 503.55,
  'standard_rating': 0.89,
  'total_reviews': 843},
 {'composite': 89.11,
  'location': '500 Washington St, San Francisco, CA 94111, United States',
  'name': 'Cafe Me',
  'price_range': 1,
  'rating_weight': 133.65,
  'standard_rating': 0.87,
  'total_reviews': 368},
 {'composite': 82.06,
  'location': '1 California St, San Francisco, CA 94111, United States',
  'name': 'eatsa',
  'price_range': 1,
  'rating_weight': 193.05,
  'standard_rating': 0.88,
  'total_reviews': 613},
 {'composite': 83.16,
  'location': '566 Columbus Ave, San Francisco, CA 94133, United States',
  'name': "Mario's Bohemian Cigar Store Cafe",
  'price_range': 1,
  'rating_weight': 325.35,
  'standard_rating': 0.89,
  'total_reviews': 751},
 {'composite': 82.71,
  'location': '915 Kearny St, San Francisco, CA 94133, United States',
  'name': 'Chong Qing Xiao Mian',
  'price_range': 1,
  'rating_weight': 232.2,
  'standard_rating': 0.87,
  'total_reviews': 483},
 {'composite': 81.94,
  'location': '618 Broadway, San Francisco, CA 94133, United States',
  'name': "Sam's",
  'price_range': 1,
  'rating_weight': 228.15,
  'standard_rating': 0.87,
  'total_reviews': 674},
 {'composite': 89.68,
  'location': '2826 Jones St, San Francisco, CA 94133, United States',
  'name': 'Carmel Pizza Company',
  'price_range': 1,
  'rating_weight': 133.65,
  'standard_rating': 0.88,
  'total_reviews': 698}]
    insert_db(rest_list, price_range)
